### ISSUE TITLE
compile issuce

### ISSUE THREAD

**Issue by darin-lao** [iris-contrib/plugin#1]
github.com/iris-contrib/plugin/iriscontrol
..\github.com\iris-contrib\plugin\iriscontrol\iriscontrol.go:96: i.child.UseEngine undefined (type *iris.Framework has no field or method UseEngine)

**Comment by kataras** [comment]
Yes, this is because of v4 alpha.1 release, please upgrade iris ( https://github.com/kataras/iris/blob/master/HISTORY.md#history ). The v3 release has its own [examples branch](https://github.com/iris-contrib/examples/tree/v3] and [v3 branch on kataras/iris](https://github.com/kataras/iris/tree/v3) but the middleware & plugins are always up-to-date ( gitbook updates the next version's day)
